### ISSUE TITLE
Le programe ne se ferme pas

### ISSUE THREAD

**Issue by PastaLaPate** [Program132/French-Programming-Language#2]
En utilisant le code suivant 
```
variable entier a -> 15;

tant que a = 10, decrementer 1 {
    envoyer a;
}
envoyer a;
```
Le program fpl ne se ferme pas

**Comment by Program132** [comment]
Les boucles ont été supprimés du langage actuellement mais elles vont être remises dans le projet. Cependant, je suis au courant du problème lié à la non fermeture du programme mais tu devrais donner plus de détails :), j'ai une piste d'où pourrait venir le problème.

**Comment by PastaLaPate** [comment]
C’était sur la version 1.9

**Comment by Program132** [comment]
Oui mais c'est toujours le cas je crois.
